general.import = ["~/.config/alacritty/themes/one_dark.toml"]

[window]
padding = { x = 10, y = 10 }

[font]
normal.family = "Hack Nerd Font"
bold.family = "Hack Nerd Font"
italic.family = "Hack Nerd Font"
bold_italic.family = "Hack Nerd Font"
size = 11.0
