[git_status]
format = '([$all_status$ahead_behind]($style))'

conflicted = " "
ahead      = " "
behind     = " "
diverged   = " "
stashed    = " "
staged     = " "
modified   = " "
renamed    = " "
deleted    = " "
untracked  = " "

